BEGIN;

WITH dist (unidade_nome, item_num, quantidade) AS (
VALUES
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 1, 68),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 2, 49),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 3, 21),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 4, 2),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 5, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 11, 13),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 14, 4),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 15, 3),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 17, 2),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 19, 9),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 20, 59),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 21, 6),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 22, 11),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 23, 7),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 24, 5),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 25, 14),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 26, 6),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 27, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 44, 168),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 45, 84),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 13, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 28, 1059),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 29, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 30, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 31, 2),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 33, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 35, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 36, 418),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 37, 32),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 38, 3),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 39, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 40, 17),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 41, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 42, 1),
  ('Fórum Geral Desembargador César Montenegro – Porto Velho – RO', 43, 324),
  ('Edifício Sede do PJRO – Porto Velho – RO', 1, 54),
  ('Edifício Sede do PJRO – Porto Velho – RO', 2, 32),
  ('Edifício Sede do PJRO – Porto Velho – RO', 3, 4),
  ('Edifício Sede do PJRO – Porto Velho – RO', 4, 2),
  ('Edifício Sede do PJRO – Porto Velho – RO', 5, 1),
  ('Edifício Sede do PJRO – Porto Velho – RO', 11, 7),
  ('Edifício Sede do PJRO – Porto Velho – RO', 32, 1),
  ('Edifício Sede do PJRO – Porto Velho – RO', 34, 2),
  ('Edifício Sede do PJRO – Porto Velho – RO', 14, 8),
  ('Edifício Sede do PJRO – Porto Velho – RO', 15, 2),
  ('Edifício Sede do PJRO – Porto Velho – RO', 16, 2),
  ('Edifício Sede do PJRO – Porto Velho – RO', 17, 2),
  ('Edifício Sede do PJRO – Porto Velho – RO', 19, 4),
  ('Edifício Sede do PJRO – Porto Velho – RO', 20, 2),
  ('Edifício Sede do PJRO – Porto Velho – RO', 21, 23),
  ('Edifício Sede do PJRO – Porto Velho – RO', 22, 5),
  ('Edifício Sede do PJRO – Porto Velho – RO', 23, 4),
  ('Edifício Sede do PJRO – Porto Velho – RO', 24, 2),
  ('Edifício Sede do PJRO – Porto Velho – RO', 25, 6),
  ('Edifício Sede do PJRO – Porto Velho – RO', 26, 4),
  ('Edifício Sede do PJRO – Porto Velho – RO', 27, 1),
  ('Edifício Sede do PJRO – Porto Velho – RO', 44, 130),
  ('Edifício Sede do PJRO – Porto Velho – RO', 45, 34),
  ('Edifício Sede do PJRO – Porto Velho – RO', 6, 7),
  ('Edifício Sede do PJRO – Porto Velho – RO', 7, 6),
  ('Edifício Sede do PJRO – Porto Velho – RO', 8, 9),
  ('Edifício Sede do PJRO – Porto Velho – RO', 9, 8),
  ('Edifício Sede do PJRO – Porto Velho – RO', 10, 21),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 1, 21),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 2, 20),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 3, 3),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 4, 1),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 11, 4),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 14, 2),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 15, 2),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 16, 1),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 17, 1),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 19, 4),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 21, 5),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 22, 3),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 23, 2),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 24, 1),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 25, 3),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 26, 2),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 27, 1),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 44, 57),
  ('EMERON – Escola de Magistratura de Rondônia – Porto Velho – RO', 45, 9),
  ('Centro de Apoio Logístico – Porto Velho - RO', 1, 11),
  ('Centro de Apoio Logístico – Porto Velho - RO', 2, 17),
  ('Centro de Apoio Logístico – Porto Velho - RO', 3, 2),
  ('Centro de Apoio Logístico – Porto Velho - RO', 4, 2),
  ('Centro de Apoio Logístico – Porto Velho - RO', 5, 3),
  ('Centro de Apoio Logístico – Porto Velho - RO', 6, 1),
  ('Centro de Apoio Logístico – Porto Velho - RO', 7, 1),
  ('Centro de Apoio Logístico – Porto Velho - RO', 8, 2),
  ('Centro de Apoio Logístico – Porto Velho - RO', 9, 2),
  ('Centro de Apoio Logístico – Porto Velho - RO', 10, 4),
  ('Centro de Apoio Logístico – Porto Velho - RO', 11, 1),
  ('Centro de Apoio Logístico – Porto Velho - RO', 12, 1),
  ('Centro de Apoio Logístico – Porto Velho - RO', 13, 2),
  ('Centro de Apoio Logístico – Porto Velho - RO', 14, 4),
  ('Centro de Apoio Logístico – Porto Velho - RO', 15, 38),
  ('Centro de Apoio Logístico – Porto Velho - RO', 16, 4),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 1, 2),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 2, 9),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 3, 4),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 4, 1),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 11, 2),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 14, 1),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 15, 1),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 17, 1),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 19, 3),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 21, 2),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 22, 2),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 23, 1),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 24, 2),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 25, 48),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 26, 1),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 44, 23),
  ('Secretaria de Gestão de Pessoas – Porto Velho – RO', 45, 6),
  ('Anexo Administrativo – Porto Velho – RO', 1, 2),
  ('Anexo Administrativo – Porto Velho – RO', 2, 9),
  ('Anexo Administrativo – Porto Velho – RO', 3, 2),
  ('Anexo Administrativo – Porto Velho – RO', 4, 1),
  ('Anexo Administrativo – Porto Velho – RO', 11, 1),
  ('Anexo Administrativo – Porto Velho – RO', 14, 1),
  ('Anexo Administrativo – Porto Velho – RO', 15, 1),
  ('Anexo Administrativo – Porto Velho – RO', 17, 1),
  ('Anexo Administrativo – Porto Velho – RO', 19, 2),
  ('Anexo Administrativo – Porto Velho – RO', 23, 1),
  ('Anexo Administrativo – Porto Velho – RO', 24, 1),
  ('Anexo Administrativo – Porto Velho – RO', 25, 27),
  ('Anexo Administrativo – Porto Velho – RO', 44, 17),
  ('Anexo Administrativo – Porto Velho – RO', 45, 3),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 1, 3),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 2, 7),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 3, 3),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 4, 1),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 11, 1),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 14, 1),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 15, 1),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 17, 1),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 19, 3),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 21, 1),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 22, 1),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 23, 1),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 24, 2),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 25, 10),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 44, 18),
  ('Centro Cultural e Documentação Histórica – Porto Velho – RO', 45, 6),
  ('Antigo Centro Cultural e Documentação Histórica – Porto Velho – RO', 1, 1),
  ('Antigo Centro Cultural e Documentação Histórica – Porto Velho – RO', 2, 2),
  ('Antigo Centro Cultural e Documentação Histórica – Porto Velho – RO', 11, 1),
  ('Antigo Centro Cultural e Documentação Histórica – Porto Velho – RO', 19, 2),
  ('Antigo Centro Cultural e Documentação Histórica – Porto Velho – RO', 44, 5),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 1, 2),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 2, 12),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 3, 2),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 4, 1),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 11, 2),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 34, 1),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 14, 1),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 15, 1),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 16, 1),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 17, 1),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 19, 4),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 20, 4),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 21, 4),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 22, 2),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 23, 1),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 24, 2),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 25, 32),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 44, 29),
  ('Fórum Ministro Aliomar Baleeiro – Alta Floresta do Oeste - RO', 45, 7),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 1, 2),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 2, 10),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 3, 2),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 4, 1),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 11, 2),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 14, 1),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 34, 1),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 15, 1),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 16, 1),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 17, 1),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 19, 3),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 20, 2),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 21, 4),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 22, 2),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 23, 1),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 24, 2),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 25, 38),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 44, 29),
  ('Fórum Jurista Júlio Guimarães Lima – Alvorada do Oeste – RO', 45, 2),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 1, 20),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 2, 25),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 3, 2),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 4, 2),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 5, 5),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 6, 1),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 7, 1),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 8, 1),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 9, 2),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 10, 2),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 11, 6),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 12, 7),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 13, 5),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 14, 6),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 15, 3),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 16, 2),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 17, 30),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 18, 2),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 19, 1),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 20, 72),
  ('Fórum Juiz Edelçon Inocêncio - Ariquemes - RO', 21, 11),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 1, 3),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 2, 10),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 3, 2),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 4, 1),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 11, 2),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 34, 1),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 14, 1),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 15, 1),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 16, 1),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 17, 1),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 19, 3),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 20, 2),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 21, 4),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 22, 2),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 23, 2),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 24, 2),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 25, 40),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 44, 29),
  ('Fórum Jorge Gurgel do Amaral Neto – Buritis – RO', 45, 4),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 1, 14),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 2, 15),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 3, 13),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 4, 1),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 11, 2),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 12, 1),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 32, 1),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 14, 1),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 15, 2),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 16, 1),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 17, 1),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 18, 1),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 19, 3),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 20, 5),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 21, 6),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 22, 5),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 23, 3),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 24, 1),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 25, 38),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 26, 3),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 44, 56),
  ('Fórum Desembargador Aldo Alberto Castanheira Silva - Cacoal – RO', 45, 16),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 1, 3),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 2, 10),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 3, 2),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 4, 1),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 11, 2),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 14, 1),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 34, 1),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 15, 1),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 16, 1),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 17, 1),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 19, 3),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 20, 3),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 21, 4),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 22, 2),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 23, 1),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 24, 2),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 25, 59),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 44, 29),
  ('Fórum Sobral Pinto – Cerejeiras – RO', 45, 4),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 1, 2),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 2, 12),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 3, 2),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 4, 1),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 11, 2),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 14, 1),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 33, 1),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 15, 1),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 16, 1),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 17, 1),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 19, 4),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 20, 5),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 21, 5),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 22, 2),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 23, 1),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 24, 1),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 25, 36),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 44, 35),
  ('Fórum Juiz Joel Quaresma Moura – Colorado do Oeste – RO', 45, 2),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 1, 4),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 2, 14),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 3, 2),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 4, 1),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 11, 2),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 14, 1),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 33, 1),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 15, 1),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 16, 1),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 17, 1),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 19, 3),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 20, 3),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 21, 4),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 22, 2),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 23, 2),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 24, 2),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 25, 10),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 44, 36),
  ('Fórum Susy Soares Silva Gomes – Costa Marques – RO', 45, 3),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 1, 2),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 2, 13),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 3, 2),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 4, 1),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 11, 2),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 14, 1),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 33, 1),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 15, 1),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 16, 1),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 17, 1),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 18, 1),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 19, 3),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 20, 3),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 21, 4),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 22, 2),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 23, 1),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 24, 3),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 25, 46),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 44, 30),
  ('Fórum Ministro Miguel Seabra Fagundes – Espigão do Oeste – RO', 45, 6),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 1, 15),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 2, 5),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 4, 2),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 12, 1),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 14, 1),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 33, 1),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 15, 1),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 16, 1),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 17, 2),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 18, 2),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 19, 2),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 20, 4),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 21, 4),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 22, 2),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 23, 1),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 24, 2),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 25, 45),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 44, 35),
  ('Fórum Nelson Hungria – Guajará Mirim – RO', 45, 4),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 1, 42),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 2, 22),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 3, 9),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 4, 2),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 11, 6),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 12, 1),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 32, 1),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 34, 1),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 14, 3),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 15, 2),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 17, 2),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 19, 5),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 20, 20),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 21, 25),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 22, 2),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 23, 3),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 24, 2),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 25, 130),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 26, 5),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 27, 1),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 44, 101),
  ('Fórum Desembargador Sérgio Alberto Nogueira de Lima – Ji-Paraná – RO', 45, 39),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 1, 11),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 2, 15),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 3, 6),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 4, 1),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 11, 3),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 14, 1),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 33, 1),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 15, 2),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 16, 1),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 17, 1),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 19, 4),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 20, 6),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 21, 6),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 22, 2),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 23, 2),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 24, 4),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 25, 53),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 26, 2),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 44, 45),
  ('Fórum Ministro Victor Nunes Leal – Jaru – RO', 45, 16),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 1, 3),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 2, 12),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 4, 1),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 11, 2),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 34, 1),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 14, 1),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 15, 1),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 16, 1),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 17, 1),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 19, 3),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 20, 4),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 21, 4),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 22, 2),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 23, 1),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 24, 3),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 25, 28),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 44, 31),
  ('Fórum José Pedro do Couto – Machadinho do Oeste – RO', 45, 5),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 1, 2),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 2, 13),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 3, 2),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 4, 1),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 11, 2),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 33, 1),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 14, 1),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 15, 1),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 16, 1),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 17, 1),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 19, 3),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 20, 2),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 21, 4),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 22, 2),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 23, 1),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 24, 2),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 25, 33),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 44, 32),
  ('Fórum Juiz José de Melo Silva – Nova Brasilândia – RO', 45, 2),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 1, 12),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 2, 16),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 3, 3),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 4, 1),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 11, 3),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 33, 1),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 14, 1),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 15, 1),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 16, 1),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 17, 1),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 19, 3),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 20, 9),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 21, 7),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 22, 4),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 23, 2),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 24, 1),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 25, 63),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 26, 3),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 44, 46),
  ('Fórum Desembargador Cássio Rodolfo Sbarzi Guedes – Ouro Preto do Oeste – RO', 45, 17),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 1, 2),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 2, 14),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 3, 2),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 4, 1),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 11, 2),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 34, 1),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 14, 1),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 15, 1),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 16, 1),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 17, 1),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 19, 4),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 20, 4),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 21, 4),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 22, 2),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 23, 1),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 24, 2),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 25, 48),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 44, 31),
  ('Fórum Professor Pontes de Miranda – Presidente Médici – RO', 45, 7),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 1, 25),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 2, 11),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 3, 11),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 4, 2),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 11, 4),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 32, 1),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 14, 2),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 15, 3),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 16, 1),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 17, 2),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 19, 3),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 20, 10),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 21, 9),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 22, 5),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 23, 2),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 26, 3),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 44, 61),
  ('Fórum Ministro Hermes de Lima – Pimenta Bueno – RO', 45, 25),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 1, 12),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 2, 16),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 3, 8),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 4, 1),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 11, 3),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 32, 1),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 14, 1),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 15, 1),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 17, 1),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 19, 4),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 20, 2),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 21, 4),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 22, 5),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 23, 3),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 24, 2),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 25, 8),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 27, 1),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 44, 30),
  ('Fórum Juiz Eurico Soares Montenegro – Rolim de Moura – RO', 45, 2),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 1, 2),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 2, 13),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 3, 3),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 4, 1),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 11, 2),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 33, 1),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 14, 2),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 15, 1),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 16, 1),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 17, 1),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 18, 3),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 19, 4),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 20, 6),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 21, 3),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 22, 2),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 23, 1),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 24, 1),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 25, 3),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 44, 34),
  ('Fórum Sebastião Souza Moura – Santa Luzia do Oeste – RO', 45, 5),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 1, 3),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 2, 10),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 3, 2),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 4, 1),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 11, 2),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 34, 1),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 14, 1),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 15, 1),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 16, 1),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 17, 1),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 19, 3),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 20, 2),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 21, 4),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 22, 2),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 23, 1),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 24, 2),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 25, 45),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 44, 29),
  ('Fórum de São Francisco do Guaporé – São Francisco do Guaporé – RO', 45, 3),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 1, 2),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 2, 15),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 3, 2),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 4, 1),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 11, 2),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 33, 1),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 14, 1),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 15, 1),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 16, 1),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 17, 1),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 19, 5),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 20, 4),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 21, 4),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 22, 2),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 23, 1),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 24, 2),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 25, 42),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 44, 33),
  ('Fórum Anízio Garcia Martins – São Miguel do Guaporé – RO', 45, 7),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 1, 12),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 2, 36),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 3, 4),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 4, 2),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 11, 2),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 12, 1),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 32, 1),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 14, 1),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 15, 2),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 16, 1),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 17, 2),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 18, 1),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 19, 5),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 20, 12),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 21, 15),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 22, 5),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 23, 3),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 24, 2),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 25, 8),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 27, 1),
  ('Fórum Desembargador Leal Fagundes – Novo Fórum de Vilhena – RO', 44, 100),
  ('Fórum Digital – Candeias do Jamari – RO', 1, 4),
  ('Fórum Digital – Candeias do Jamari – RO', 2, 4),
  ('Fórum Digital – Candeias do Jamari – RO', 3, 1),
  ('Fórum Digital – Candeias do Jamari – RO', 11, 1),
  ('Fórum Digital – Candeias do Jamari – RO', 34, 1),
  ('Fórum Digital – Candeias do Jamari – RO', 19, 1),
  ('Fórum Digital – Candeias do Jamari – RO', 21, 1),
  ('Fórum Digital – Candeias do Jamari – RO', 44, 10),
  ('Fórum Digital – Candeias do Jamari – RO', 45, 1),
  ('Fórum Digital – Itapuã do Oeste – RO', 1, 4),
  ('Fórum Digital – Itapuã do Oeste – RO', 2, 4),
  ('Fórum Digital – Itapuã do Oeste – RO', 3, 1),
  ('Fórum Digital – Itapuã do Oeste – RO', 11, 1),
  ('Fórum Digital – Itapuã do Oeste – RO', 34, 1),
  ('Fórum Digital – Itapuã do Oeste – RO', 19, 1),
  ('Fórum Digital – Itapuã do Oeste – RO', 21, 1),
  ('Fórum Digital – Itapuã do Oeste – RO', 44, 10),
  ('Fórum Digital – Itapuã do Oeste – RO', 45, 1),
  ('Fórum Digital – Cujubim – RO', 1, 4),
  ('Fórum Digital – Cujubim – RO', 2, 4),
  ('Fórum Digital – Cujubim – RO', 3, 1),
  ('Fórum Digital – Cujubim – RO', 11, 1),
  ('Fórum Digital – Cujubim – RO', 34, 1),
  ('Fórum Digital – Cujubim – RO', 19, 1),
  ('Fórum Digital – Cujubim – RO', 21, 1),
  ('Fórum Digital – Cujubim – RO', 44, 10),
  ('Fórum Digital – Cujubim – RO', 45, 1),
  ('Fórum Digital – Alto Paraíso – RO', 1, 4),
  ('Fórum Digital – Alto Paraíso – RO', 2, 4),
  ('Fórum Digital – Alto Paraíso – RO', 3, 1),
  ('Fórum Digital – Alto Paraíso – RO', 11, 1),
  ('Fórum Digital – Alto Paraíso – RO', 34, 1),
  ('Fórum Digital – Alto Paraíso – RO', 19, 1),
  ('Fórum Digital – Alto Paraíso – RO', 21, 1),
  ('Fórum Digital – Alto Paraíso – RO', 44, 10),
  ('Fórum Digital – Alto Paraíso – RO', 45, 1),
  ('Fórum Digital – Extrema – RO', 1, 7),
  ('Fórum Digital – Extrema – RO', 2, 3),
  ('Fórum Digital – Extrema – RO', 3, 2),
  ('Fórum Digital – Extrema – RO', 11, 1),
  ('Fórum Digital – Extrema – RO', 34, 1),
  ('Fórum Digital – Extrema – RO', 19, 1),
  ('Fórum Digital – Extrema – RO', 21, 1),
  ('Fórum Digital – Extrema – RO', 44, 2),
  ('Fórum Digital – Extrema – RO', 45, 11),
  ('Fórum Digital – Mirante da Serra – RO', 1, 1),
  ('Fórum Digital – Mirante da Serra – RO', 2, 1),
  ('Fórum Digital – Mirante da Serra – RO', 3, 1),
  ('Fórum Digital – Mirante da Serra – RO', 11, 1),
  ('Fórum Digital – Mirante da Serra – RO', 44, 2),
  ('Fórum Digital – Mirante da Serra – RO', 45, 1),
  ('Fórum Digital – Campo Novo de Rondônia – RO', 1, 4),
  ('Fórum Digital – Campo Novo de Rondônia – RO', 2, 4),
  ('Fórum Digital – Campo Novo de Rondônia – RO', 3, 1),
  ('Fórum Digital – Campo Novo de Rondônia – RO', 11, 1),
  ('Fórum Digital – Campo Novo de Rondônia – RO', 34, 1),
  ('Fórum Digital – Campo Novo de Rondônia – RO', 19, 1),
  ('Fórum Digital – Campo Novo de Rondônia – RO', 21, 1),
  ('Fórum Digital – Campo Novo de Rondônia – RO', 44, 10),
  ('Fórum Digital – Campo Novo de Rondônia – RO', 45, 1),
  ('Fórum Digital – Monte Negro – RO', 1, 4),
  ('Fórum Digital – Monte Negro – RO', 2, 4),
  ('Fórum Digital – Monte Negro – RO', 3, 1),
  ('Fórum Digital – Monte Negro – RO', 11, 1),
  ('Fórum Digital – Monte Negro – RO', 34, 1),
  ('Fórum Digital – Monte Negro – RO', 19, 1),
  ('Fórum Digital – Monte Negro – RO', 21, 1),
  ('Fórum Digital – Monte Negro – RO', 44, 10),
  ('Fórum Digital – Monte Negro – RO', 45, 1),
  ('Fórum Digital – Chupinguaia – RO', 1, 4),
  ('Fórum Digital – Chupinguaia – RO', 2, 4),
  ('Fórum Digital – Chupinguaia – RO', 3, 1),
  ('Fórum Digital – Chupinguaia – RO', 11, 1),
  ('Fórum Digital – Chupinguaia – RO', 34, 1),
  ('Fórum Digital – Chupinguaia – RO', 19, 1),
  ('Fórum Digital – Chupinguaia – RO', 21, 1),
  ('Fórum Digital – Chupinguaia – RO', 44, 10),
  ('Fórum Digital – Chupinguaia – RO', 45, 1)
)
INSERT INTO public.unidade_equipamentos (unidade_id, equipamento_id, quantidade)
SELECT u.id, ec.id, d.quantidade
FROM dist d
JOIN public.unidades u ON u.nome = d.unidade_nome
JOIN public.equipamentos_catalogo ec ON ec.item_num = d.item_num
ON CONFLICT (unidade_id, equipamento_id) DO UPDATE SET
  quantidade = EXCLUDED.quantidade,
  updated_at = now();

COMMIT;
